#if !defined(AFX_HDFCOMMAGENT_H__EA1C31E9_E73B_4C31_AE61_920780CAF043__INCLUDED_)
#define AFX_HDFCOMMAGENT_H__EA1C31E9_E73B_4C31_AE61_920780CAF043__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHDFCommAgent wrapper class
//#include "HDFStruct.h"

class CHDFCommAgent : public CWnd
{
protected:
	DECLARE_DYNCREATE(CHDFCommAgent)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= {0x2A7B5BEF, 0x49EE, 0x4219, {0x98, 0x33, 0xdb, 0x04, 0xd0, 0x78, 0x76, 0xcf } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ 
		m_pParentWnd = pParentWnd;

		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CWnd *m_pParentWnd;

// Operations
public:
	void AboutBox();
	long CommInit(long nType=0);
	void CommTerminate(long bSocketClose);
	long CommLogin(LPCTSTR sUserID, LPCTSTR sPwd, LPCTSTR sCertPwd);
	long CommLogout(LPCTSTR sUserID);
	long CommRqData(LPCTSTR sTrCode, LPCTSTR sInputData, LONG nLength, LPCTSTR sPrevOrNext);
	long CommSetBroad(LPCTSTR sJongmokCode, long nRealType);
	long CommRemoveBroad(LPCTSTR sJongmokCode, long nRealType);
	long CommGetRepeatCnt(LPCTSTR sJongmokCode, long nRealType, LPCTSTR sFieldName);
	CString CommGetData(LPCTSTR sJongmokCode, long nRealType, LPCTSTR sFieldName, long nIndex, LPCTSTR sInnerFieldName);
	CString CommGetDataDirect(LPCTSTR sJongmokCode, long nRealType, long nOffset, long nLength, long nPointLength, LPCTSTR sDataType);
	long CommGetConnectState();
	long CommFIDRqData(LPCTSTR sFidCode, LPCTSTR sInputData, LPCTSTR sReqFidList, long nLength, LPCTSTR sPrevOrNext);
	long CommSetJumunChe(LPCTSTR sUserID, LPCTSTR sAccNo);
	long CommRemoveJumunChe(LPCTSTR sUserID, LPCTSTR sAccNo);
	long CommJumunSvr(LPCTSTR sTrCode, LPCTSTR sInputData);
	long CommAccInfo();
	long CommMiCheFoForAcc(LPCTSTR sAcctNo, LPCTSTR sAcctPw);
	CString CommGetDealNo(LPCTSTR sAcctNo);
	CString CommGetDataBinary(LPCTSTR sJongmokCode, long nRealType, long nOffset, long nLength, long nPointLength, LPCTSTR sDataType);

	long Transact(long hWnd, long nKey, LPCTSTR szTRCode, LPCTSTR szInput, long nInputLen, long nHeadType=0, long nAccountIndex=0);

	long Attach(long hWnd, LPCTSTR szBCType, LPCTSTR szInput, long nCodeLen, long nInputLen);
	long Detach(long hWnd, LPCTSTR szBCType, LPCTSTR szInput, long nCodeLen, long nInputLen);

	CString CommGetHWOrdPrice(LPCTSTR sSeries, LPCTSTR sPrice, long nType);

	// Excel에서 사용하기 위한 Directory 설정 - 20120522 sivas
	void SetOCXPath(LPCTSTR sOCXPath);

	// 해외에서 사용될 JMCODE.cod 파일을 만들기 위해 서버로 서비스 요청한다. - 20120529 sivas
	void CommReqMstInfo(LPCTSTR strExchCd);

	// JMCODE, MRKT, PMCODE 등.. cod파일 만들기위해 요청하는 서비스 - 20140523 anigate
	// 싹 뜯어고침.. 해외 선물/옵션 - 20150416 anigate
	// 인자값 변경. - 201603330 anigate
	void CommReqMakeCod(LPCTSTR strParam, long nMstType = 0);

	// 해외용 mst파일로 부터 정보를 반환하는 함수 - 20120806 sivas
	CString CommGetHWInfo(LPCTSTR sSeries, long nInfo);

	// 계좌정보를 반환하는 함수 추가. - 20140328 sivas
	CString CommGetAccInfo();

	CString CommGetNextKey(long nRqId, LPCTSTR sReserved);
	CString CommGetBusinessDay(long nJangubun);
	CString CommGetInfo(LPCTSTR sTag, LPCTSTR sParam = _T(""));

	//{{AFX_MSG(CHDFCommAgent)
	//afx_msg long OnGetData(WPARAM wParam, LPARAM lParam);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HDFCOMMAGENT_H__EA1C31E9_E73B_4C31_AE61_920780CAF043__INCLUDED_)
